ALTER TABLE Работники
ALTER COLUMN Телефон NVARCHAR(20)
MASKED WITH (FUNCTION = 'partial(0,"XXXXXXX",4)');

ALTER TABLE Работники
ALTER COLUMN ИИН
ADD MASKED WITH (FUNCTION = 'default()');

SELECT * FROM Работники

EXECUTE AS USER = 'User1';
SELECT * FROM Работники;
REVERT;

GRANT UNMASK TO User1;
EXECUTE AS USER = 'User1';
SELECT * FROM Работники;
REVERT;

REVOKE UNMASK FROM User1;

ALTER TABLE Работники ALTER COLUMN Телефон DROP MASKED;
ALTER TABLE Работники ALTER COLUMN ИИН DROP MASKED;

EXECUTE AS USER = 'User1';  
SELECT * FROM Работники
WHERE ИИН LIKE '900101%';
REVERT;
