ALTER TABLE Заказ
ALTER COLUMN Телефон NVARCHAR(20)
MASKED WITH (FUNCTION = 'partial(0,"XXXXXXX",4)');

ALTER TABLE Заказ
ALTER COLUMN Адрес 
ADD MASKED WITH (FUNCTION = 'partial(2,"XXXX",2)');

EXECUTE AS USER = 'AtelierUser1';
SELECT * FROM Заказ;
REVERT;

GRANT UNMASK TO AtelierUser1;
EXECUTE AS USER = 'AtelierUser1';
SELECT * FROM Заказ;
REVERT;

REVOKE UNMASK FROM AtelierUser1;

ALTER TABLE Заказ ALTER COLUMN Телефон DROP MASKED;
ALTER TABLE Заказ ALTER COLUMN Адрес DROP MASKED;

EXECUTE AS USER = 'AtelierUser1';
SELECT * FROM Заказ WHERE Телефон LIKE '%77%';
REVERT;

